<?php namespace App;

/**
 * Eloquent class to describe the tb_nota_disciplina table
 *
 * automatically generated by ModelGenerator.php
 */
class TbNotaDisciplina extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'tb_nota_disciplina';

    public $primaryKey = 'seq_nota_disciplina';

    public $timestamps = false;

    protected $fillable = array('num_nota','seq_disciplina','seq_matricula');

    public function tbDisciplina()
    {
        return $this->belongsTo('App\TbDisciplina', 'seq_disciplina', 'seq_disciplina');
    }

    public function tbMatricula()
    {
        return $this->belongsTo('App\TbMatricula', 'seq_matricula', 'seq_matricula');
    }

}
