<?php namespace App;

/**
 * Eloquent class to describe the tb_disciplina table
 *
 * automatically generated by ModelGenerator.php
 */
class TbDisciplina extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'tb_disciplina';

    public $primaryKey = 'seq_disciplina';

    public $timestamps = false;

    protected $fillable = array('nom_disciplina');

    public function tbNotaDisciplina()
    {
        return $this->hasMany('App\TbNotaDisciplina', 'seq_disciplina', 'seq_disciplina');
    }
}
