<?php namespace App;

/**
 * Eloquent class to describe the tb_matricula table
 *
 * automatically generated by ModelGenerator.php
 */
class TbMatricula extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'tb_matricula';

    public $primaryKey = 'seq_matricula';

    public $timestamps = false;

    public function getDates()
    {
        return array('dat_entrada_escola');
    }

    protected $fillable = array('num_matricula', 'nom_aluno', 'des_endereco', 'des_bairro', 'num_cep', 'nom_cidade',
        'cod_unidade_federacao', 'des_email', 'dat_entrada_escola');

    public function tbNotaDisciplina()
    {
        return $this->hasMany('App\TbNotaDisciplina', 'seq_matricula', 'seq_matricula');
    }
}
